// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqc90t6IfhVqQG02qyDWlixzxlVPuz7n0',
    appId: '1:761955277335:web:c364a62928c9126f295a52',
    messagingSenderId: '761955277335',
    projectId: 'chat-2ca13',
    authDomain: 'chat-2ca13.firebaseapp.com',
    storageBucket: 'chat-2ca13.firebasestorage.app',
    measurementId: 'G-2434H1SG25',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGMQr3aUnyFImlgkzmkRnoN90iODfsn_s',
    appId: '1:761955277335:android:b663d66f33137a55295a52',
    messagingSenderId: '761955277335',
    projectId: 'chat-2ca13',
    storageBucket: 'chat-2ca13.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxrCoEwwlA4U_Y3JDOAX8ybbHiYXOuW-U',
    appId: '1:761955277335:ios:9d9142083324849a295a52',
    messagingSenderId: '761955277335',
    projectId: 'chat-2ca13',
    storageBucket: 'chat-2ca13.firebasestorage.app',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxrCoEwwlA4U_Y3JDOAX8ybbHiYXOuW-U',
    appId: '1:761955277335:ios:9d9142083324849a295a52',
    messagingSenderId: '761955277335',
    projectId: 'chat-2ca13',
    storageBucket: 'chat-2ca13.firebasestorage.app',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCqc90t6IfhVqQG02qyDWlixzxlVPuz7n0',
    appId: '1:761955277335:web:3f6191cea0a47712295a52',
    messagingSenderId: '761955277335',
    projectId: 'chat-2ca13',
    authDomain: 'chat-2ca13.firebaseapp.com',
    storageBucket: 'chat-2ca13.firebasestorage.app',
    measurementId: 'G-BL1VQF8G2Q',
  );
}
